name=input("Enter Your Name : ")
roll=int(input("Enter Your Roll No : "))
percent=int(input("Enter percentage in python : "))
gender=input("Enter Male or Female : ")
age=int(input("Enter the age : "))
print()
print("The information about the student")
print("The name of the student : ",name)
print("The roll number of the student: ",roll)
print("The percentage: ",percent)
print("The Gender of the student :",gender)
print("The Age of the student is : ",age)
print("Type of variable name : ",type(name))
print("Type of variable roll: ",type(roll))
print("Type of variable percentage: ",type(percent))
print("Type of variable Gender :",type(gender))
print("Type of variable Age : ",type(age))
        
